proxy-providers:
  MODEM1:
    type: file
    path: "./proxy_provider/modem1.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 10
  MODEM2:
    type: file
    path: "./proxy_provider/modem2.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 10
proxy-groups:
- name: MODEM1
  type: select
  disable-udp: false
  interface-name: usb0
  use:
  - MODEM1
- name: MODEM2
  type: select
  disable-udp: false
  interface-name: eth1
  use:
  - MODEM2
- name: LB-2-MODEM
  type: load-balance
  strategy: round-robin
  disable-udp: false
  proxies:
  - MODEM1
  - MODEM2
  url: http://www.gstatic.com/generate_204
  interval: 60
- name: SERVER-UMUM
  type: select
  disable-udp: false
  proxies:
  - LB-2-MODEM
  - MODEM1
  - MODEM2
  - DIRECT
- name: SERVER-INDO
  type: select
  disable-udp: false
  proxies:
  - LB-2-MODEM
  - MODEM1
  - MODEM2
  - DIRECT
- name: SERVER-GAME
  type: select
  disable-udp: false
  proxies:
  - LB-2-MODEM
  - MODEM1
  - MODEM2
  - DIRECT
- name: BLOCK-IKLAN
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - LB-2-MODEM
rule-providers:
  Game:
    type: file
    behavior: classical
    path: "./rule_provider/game.yaml"
  PortGame:
    type: file
    behavior: classical
    path: "./rule_provider/portgame.yaml"
  Umum:
    type: file
    behavior: classical
    path: "./rule_provider/umum.yaml"
  indo:
    type: file
    behavior: classical
    path: "./rule_provider/indo.yaml"
  Sosmed:
    type: file
    behavior: classical
    path: "./rule_provider/sosmed.yaml"
  Streaming:
    type: file
    behavior: classical
    path: "./rule_provider/streaming.yaml"
  Bankid:
    type: file
    behavior: domain
    path: "./rule_provider/bankid.yaml"
  Tiktok:
    type: file
    behavior: domain
    path: "./rule_provider/tiktok.yaml"
  Meta:
    type: file
    behavior: domain
    path: "./rule_provider/meta.yaml"
  Oisd_small:
    type: http
    behavior: classical
    path: "./rule_provider/oisd_small.yaml"
    url: https://raw.githubusercontent.com/hillz2/openclash_adblock/main/oisd_small.yaml
    interval: 28800
rules:
- RULE-SET,Umum,SERVER-UMUM
- RULE-SET,Game,SERVER-GAME
- RULE-SET,PortGame,SERVER-GAME
- RULE-SET,indo,SERVER-INDO
- RULE-SET,Sosmed,SERVER-INDO
- RULE-SET,Streaming,SERVER-UMUM
- RULE-SET,Bankid,SERVER-INDO
- RULE-SET,Tiktok,SERVER-UMUM
- RULE-SET,Meta,SERVER-INDO
- RULE-SET,Oisd_small,BLOCK-IKLAN
- MATCH,SERVER-UMUM
dns:
  proxy-server-nameserver:
    - 112.215.203.246
    - 112.215.203.247
    - 112.215.203.248
    - 112.215.203.254
    - 112.215.198.248
    - 112.215.198.254
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
  fallback:
    - 1.0.0.1
    - 8.8.4.4
    - 149.112.112.112
ntp:
  servers:
    - pool.ntp.org
    - id.pool.ntp.org
    - time.google.com
  option:
    maxpoll: 6
    minpoll: 3